version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
  web:
    build: .
    command: gunicorn my_site.wsgi:application -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment: 
      - "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}"
      - "DEBUG=${DEBUG}"
  
volumes:
  postgres_data: